server:
  port: 8888

spring:
  application:
    name: tour-of-heroes-server
#  datasource:
#    url: jdbc:postgresql://${POSTGRES_DB_HOST}:5432/${POSTGRES_DB_NAME}
#    username: ${POSTGRES_DB_USERNAME}
#    password: ${POSTGRES_DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update, validate): with "validate" the database
    # schema will be validated and will not change
    hibernate.ddl-auto: create-drop
    # Allows to Hibernate to generate SQL optimized for a particular DBMS
#    properties:
#      hibernate:
#        jdbc:
#          batch_size: 20
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
    change-log: classpath:db/liquibase-changelog.xml
logging:
  level:
    by.zenov: debug